apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.configServer.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: odoru
    app.kubernetes.io/component: config-server
    app.kubernetes.io/instance: {{ .Values.services.configServer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.services.configServer.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: odoru
        app.kubernetes.io/component: config-server
        app.kubernetes.io/instance: {{ .Values.services.configServer.name }}
    spec:
      serviceAccountName: {{ .Values.security.serviceAccount.name }}
      containers:
        - name: {{ .Values.services.configServer.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.services.configServer.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.configServer.port }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.configServer.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.configServer.port }}
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6

          resources:
            requests:
              cpu: {{ .Values.resources.spring.requests.cpu | quote }}
              memory: {{ .Values.resources.spring.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.spring.limits.cpu | quote }}
              memory: {{ .Values.resources.spring.limits.memory | quote }}

          env:
            - name: SERVER_PORT
              value: {{ .Values.services.configServer.port | quote }}

            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
              value: "file:/config-repo"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.configServer.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: odoru
    app.kubernetes.io/component: config-server
    app.kubernetes.io/instance: {{ .Values.services.configServer.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Values.services.configServer.name }}
  ports:
    - name: http
      port: {{ .Values.services.configServer.port }}
      targetPort: {{ .Values.services.configServer.port }}
