{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: odoru-default-deny-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: odoru
    app.kubernetes.io/component: network-policy
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: odoru-allow-same-namespace
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: odoru
    app.kubernetes.io/component: network-policy
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: odoru-allow-ingress-controller
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: odoru
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: front
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
{{- end }}
