FROM docker.io/eclipse-temurin:17-jre-alpine
LABEL org.opencontainers.image.title="odoru-course-service"
LABEL org.opencontainers.image.description="Odoru course microservice"
LABEL org.opencontainers.image.version="1.0.0"

WORKDIR /app

RUN addgroup -S odoru && adduser -S odoru -G odoru

COPY services/course-service/target/*.jar app.jar

USER odoru

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/app/app.jar"]